version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: tacaro-backend:latest
    container_name: taCaro-backend
    ports:
      - "9090:9090"
    env_file:
      - dev.env
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pemar 
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always
