basePath: /api-v1
definitions:
  models.RequestData:
    properties:
      url:
        description: URL to be fetched and processed.
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API que processa notas fiscais e extrai informações.
  title: taCaro Backend API
  version: "1.0"
paths:
  /processarQRCode:
    post:
      consumes:
      - application/json
      description: Receives a URL!, performs a GET request and extracts HTML info.
      parameters:
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RequestData'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Log and extract info from URL
      tags:
      - api-v1
swagger: "2.0"
